---
- hosts: all
  gather_facts: yes  
  tasks:
  - name: Removing OLD PYTHON file from the Remote Machine
    file:
      path: /home/emmad/02-Get_OS_Details.py 
      state: absent
  - name: Removing OLD JSON file from the Remote Machine
    file:
      path: /home/emmad/01-Linux_Command.json
      state: absent
  - name: Removing OLD CSV file from the the Remote Machine
    file:
      path: /home/emmad/DAILY_REPORTS.csv
      state: absent
  - name: Copy the 02-Get_OS_Details.py file to the Remote home directory
    copy:
      src: /home/emmad/ansible/02-Get_OS_Details.py 
      dest: /home/emmad
      mode: 0755
      owner: emmad
      group: emmad
  - name: copy to json file 01-Linux_Command.json to the Remote home directory
    copy:
      src: /home/emmad/ansible/01-Linux_Command.json
      dest: /home/emmad/
      owner: emmad
      group: emmad
  - name: Executing the python script from the Remote endpoints 
    command: /home/emmad/02-Get_OS_Details.py
  - name: Fetching the Daily_Report.csv to the Ansible Master Machine 
    fetch:
      src: /home/emmad/Daily_Report.csv
        # dest: /home/emmad/ansible/CSV/DAILY_REPORTS{{inventory_hostname}}_{{ansible_date_time.minute}}.csv
      dest: /home/emmad/ansible/CSV/Daily_Report_{{inventory_hostname}}_{{ansible_date_time.time}}.csv
      flat: yes
      

